version: "3"
services:
  cors:
    restart: unless-stopped
    image: redocly/cors-anywhere
    ports:
      - "80:80"
    env_file:
      - .env
  nginx:
    restart: unless-stopped
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - sslcerts:/etc/ssl/private
    depends_on:
      - cors
    entrypoint:
      - "sh"
      - "-c"
    command: |
      "if [ ! -f /etc/ssl/private/cors.crt ]; then
        echo 'ssl certificate missing, installing openssl to create a new one'
        apt-get update && apt-get install openssl -y
        openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout /etc/ssl/private/cors.key -out /etc/ssl/private/cors.crt -subj '/CN=cors.local' -days 3650
        echo 'Created new ssl certificate'
      fi
      exec nginx -g 'daemon off;'"
volumes:
  sslcerts:
